### ISSUE TITLE
Failure with jade file

### ISSUE THREAD

**Issue by baskaal** [Aratramba/pug-doc-html#6]
``` jade
//- @jadedoc
  name: foo
  description: foo
  arguments:
    one: foo
    two: faa

mixin foo(one, two)
  p= one
  p= two

//- @jadedoc
  name: faa

div.faa


//- @jadedoc
  name: baz

div.baz
```

Error:

``` bash
Generating Jade-doc

* foo - <p>foo</p><p>faa</p>
undefined:1
"test.jade","source":"div.faa","output":"<div class=\"faa\"></div>"}{"meta":{"
                                                                    ^
SyntaxError: Unexpected token {
    at Object.parse (native)
    at DestroyableTransform._transform (/Users/bastard/Desktop/jade-doc-test/node_modules/jade-doc-html/index.js:137:38)
    at DestroyableTransform.Transform._read (/Users/bastard/Desktop/jade-doc-test/node_modules/jade-doc-html/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/bastard/Desktop/jade-doc-test/node_modules/jade-doc-html/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/bastard/Desktop/jade-doc-test/node_modules/jade-doc-html/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/bastard/Desktop/jade-doc-test/node_modules/jade-doc-html/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/Users/bastard/Desktop/jade-doc-test/node_modules/jade-doc-html/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

**Comment by Aratramba** [comment]
confirmed for node 4.1 and 0.12

**Comment by Aratramba** [comment]
same problem occurs in [jade-doc-markdown](https://github.com/Aratramba/jade-doc-markdown)

**Comment by Aratramba** [comment]
simplified case:

Save above jade script to issue6.jade.

``` bash
jade-doc issue6.jade | node stream.js
```

// stream.js

``` node
var pretty = require('pretty');
process.stdin.on('data', function(data){
  process.stdout.write(pretty(JSON.parse(data).output) +'\n');
});
```

without pretty() all works as expected.

**Comment by Aratramba** [comment]
can't seem to find the bug here. It is fixed when I add pretty() to the initial jade-doc stream instead of down the stream though. Maybe something to do with back pressure?
